# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               Shreyas Bhave
tagline:             'Biomedical Informatician'
description:         'A blog where I share my insights into politics, machine learning, and public health. Analyses of papers, articles, lectures. Explainer and opinion pieces on important issues.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Shreyas Bhave
  url:               sbhave77.github.io
  email:             sbhave@berkeley.edu

# Custom vars
version:             1.0.0
